
on: 
  pull_request: 
    types:
      - closed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master

    - name: Login
      uses: okteto/login@master
      with:
        url: https://okteto.gymshark.dev.okteto.net
        token: ${{ secrets.OKTETO_TOKEN }}
    
    - name: Delete namespace
      uses: okteto/delete-namespace@master
      with:
        namespace: go-todo-list-pr-${{ github.event.number }}
